// Detector suggestions (benchmark/gold/tagger_beats_suggest.py: BEATs only). Generated by
// benchmark/gold/tagger_refresh.py; do not edit by hand. Hidden in the tool until asked.
window.DELEGATION_SUGGEST = {
};
