// AudioSet sound names for the name box (free text is also allowed).
window.DELEGATION_VOCAB = [
"Accelerating, revving, vroom",
"Air brake",
"Air conditioning",
"Air horn, truck horn",
"Aircraft",
"Aircraft engine",
"Alarm",
"Alarm clock",
"Ambulance (siren)",
"Applause",
"Arrow",
"Artillery fire",
"Baby cry, infant cry",
"Baby laughter",
"Bang",
"Bark",
"Basketball bounce",
"Bathtub (filling or washing)",
"Battle cry",
"Bay",
"Bee, wasp, etc.",
"Beep, bleep",
"Bell",
"Bellow",
"Belly laugh",
"Bicycle",
"Bird",
"Bird flight, flapping wings",
"Bird vocalization, bird call, bird song",
"Biting",
"Bleat",
"Blender",
"Boat",
"Boat, Water vehicle",
"Boiling",
"Booing",
"Boom",
"Bow-wow",
"Breaking",
"Burping, eructation",
"Burst, pop",
"Bus",
"Busy signal",
"Buzz",
"Buzzer",
"Camera",
"Canidae, dogs, wolves",
"Cap gun",
"Car",
"Car alarm",
"Car passing by",
"Cash register",
"Cat",
"Cat communication",
"Caterwaul",
"Cattle",
"Cattle, bovinae",
"Caw",
"Cellphone buzz, vibrating alert",
"Chainsaw",
"Cheering",
"Chewing, mastication",
"Chicken, rooster",
"Children playing",
"Children shouting",
"Chink, clink",
"Chipmunk",
"Chirp, tweet",
"Chop",
"Chopping (food)",
"Chuckle, chortle",
"Civil defense siren",
"Clapping",
"Clickety-clack",
"Clip-clop",
"Clock",
"Cluck",
"Clunk",
"Coin (dropping)",
"Computer keyboard",
"Coo",
"Cooking",
"Cough",
"Crack",
"Crackle",
"Creak",
"Cricket",
"Croak",
"Crow",
"Crowd",
"Crowing, cock-a-doodle-doo",
"Crying, sobbing",
"Cupboard open or close",
"Cutlery, silverware",
"Dental drill, dentist's drill",
"Dial tone",
"Ding",
"Ding-dong",
"Dishes",
"Dishes, pots, and pans",
"Dog",
"Donkey, ass",
"Door",
"Doorbell",
"Drawer open or close",
"Drill",
"Drip",
"Duck",
"Duck call (hunting tool)",
"Electric shaver, electric razor",
"Electric toothbrush",
"Emergency vehicle",
"Engine",
"Engine knocking",
"Engine starting",
"Eruption",
"Explosion",
"Fart",
"Filing (rasp)",
"Fill (with liquid)",
"Finger snapping",
"Fire",
"Fire alarm",
"Fire engine, fire truck (siren)",
"Firecracker",
"Fireworks",
"Fixed-wing aircraft, airplane",
"Fly, housefly",
"Foghorn",
"Footsteps",
"Fowl",
"Frog",
"Frying (food)",
"Fusillade",
"Gargling",
"Gasp",
"Gears",
"Giggle",
"Glass",
"Goat",
"Gobble",
"Goose",
"Groan",
"Growling",
"Grunt",
"Gull, seagull",
"Gunshot",
"Gunshot, gunfire",
"Gurgling",
"Gush",
"Hair dryer",
"Hammer",
"Heavy engine (low frequency)",
"Helicopter",
"Hiccup",
"Hiss",
"Honk",
"Hoot",
"Horse",
"Howl",
"Ice cream truck, ice cream van",
"Idling",
"Insect",
"Jackhammer",
"Jet engine",
"Kettle whistle",
"Keys jangling",
"Knock",
"Laughter",
"Lawn mower",
"Light engine (high frequency)",
"Liquid",
"Machine gun",
"Mechanical fan",
"Medium engine (mid frequency)",
"Meow",
"Microwave oven",
"Moo",
"Mosquito",
"Motor vehicle (road)",
"Motorboat, speedboat",
"Motorcycle",
"Mouse",
"Neigh, whinny",
"Nicker",
"Non-motorized land vehicle",
"Ocean",
"Oink",
"Owl",
"Packing tape, duct tape",
"Pant",
"Patter",
"Pig",
"Pigeon, dove",
"Police car (siren)",
"Pour",
"Power tool",
"Power windows, electric windows",
"Printer",
"Propeller, airscrew",
"Pulleys",
"Pump (liquid)",
"Purr",
"Quack",
"Race car, auto racing",
"Rail transport",
"Railroad car, train wagon",
"Rain",
"Rain on surface",
"Raindrop",
"Ratchet, pawl",
"Rattle",
"Reversing beeps",
"Ringing (of resonator)",
"Ringtone",
"Roar",
"Roaring cats (lions, tigers)",
"Rodents, rats, mice",
"Rowboat, canoe, kayak",
"Run",
"Sailboat, sailing ship",
"Sanding",
"Sawing",
"Scissors",
"Screaming",
"Sewing machine",
"Shatter",
"Sheep",
"Ship",
"Shout",
"Shuffle",
"Shuffling cards",
"Sigh",
"Single-lens reflex camera",
"Sink (filling or washing)",
"Siren",
"Sizzle",
"Skateboard",
"Skidding",
"Slam",
"Sliding door",
"Slosh",
"Smash, crash",
"Smoke detector, smoke alarm",
"Snake",
"Snap",
"Sneeze",
"Snicker",
"Sniff",
"Snoring",
"Snort",
"Snort (horse)",
"Sonar",
"Sonic boom",
"Splash, splatter",
"Splinter",
"Spray",
"Squawk",
"Squeak",
"Squish",
"Steam",
"Steam whistle",
"Stir",
"Stomach rumble",
"Stream",
"Subway, metro, underground",
"Tap",
"Telephone",
"Telephone bell ringing",
"Telephone dialing, DTMF",
"Throat clearing",
"Thump, thud",
"Thunder",
"Thunderstorm",
"Thunk",
"Tick",
"Tick-tock",
"Tire squeal",
"Toilet flush",
"Tools",
"Toot",
"Toothbrush",
"Traffic noise, roadway noise",
"Train",
"Train horn",
"Train wheels squealing",
"Train whistle",
"Trickle, dribble",
"Truck",
"Turkey",
"Typewriter",
"Typing",
"Vacuum cleaner",
"Vehicle",
"Vehicle horn, car horn, honking",
"Velcro, hook and loop fastener",
"Wail, moan",
"Walk, footsteps",
"Water",
"Water tap, faucet",
"Waterfall",
"Waves, surf",
"Whale vocalization",
"Wheeze",
"Whimper",
"Whimper (dog)",
"Whistle",
"Whoop",
"Whoosh, swoosh, swish",
"Wildfire",
"Wobble",
"Wolf-whistling",
"Wood",
"Writing",
"Yak",
"Yawn",
"Yell",
"Yip",
"Zipper (clothing)"
];
